# Generated by Django 2.1.7 on 2019-02-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='message',
        ),
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.IntegerField(default=5),
        ),
    ]
