# Generated by Django 2.1.7 on 2019-02-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190226_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
